package main;

public enum FielderDecision {
	UNKNOWN,CHASE_BALL,TAG_RUNNER,COVER_FIRST,COVER_SECOND,COVER_THRID,COVER_HOME,THROW_FIRST,THROW_SECOND,THROW_THIRD,THROW_HOME,THROW_CUTOFF,BECOME_CUTOFF
}
